### ISSUE TITLE
Expected a provider named 'null' , did you forget to register it?

### ISSUE THREAD

**Issue by pwfisher** [stefanpenner/ember-inflector#100]
Using ember inflector within an addon, we get this cryptic error. Does it mean anything to you?

```
Error: Expected a provider named 'null' , did you forget to register it?
    at null.close (singularize.js:20)
```

**Comment by stefanpenner** [comment]
I don't believe we have code that could cause this.

**Comment by fivetanley** [comment]
If you can create a new project (via `ember new`) that demonstrates this error, please feel free to open a new issue. We don't have any code like this in ember inflector that would throw such an error.

**Comment by pwfisher** [comment]
This appears to have been an `ember-simple-auth` issue. Sorry.
https://github.com/simplabs/ember-simple-auth/issues/345
