### ISSUE TITLE
1.9.2 showing as latest release

### ISSUE THREAD

**Issue by HeroicEric** [stefanpenner/ember-inflector#103]
The latest tag (1.9.4) is not being displayed as the latest release on the [releases](https://github.com/stefanpenner/ember-inflector/releases) page.

![](https://dl.dropboxusercontent.com/spa/ibxdnt7kjmsxult/6m3wa8ie.png)

**Comment by olivia** [comment]
I've added a release for the latest tag (1.9.5), thanks @HeroicEric!
