### ISSUE TITLE
two minor issues with ember-cli-addon

### ISSUE THREAD

**Issue by mattmarcum** [stefanpenner/ember-inflector#54]
1) the bower package includes a source map line that will cause a browser fetch that fails. Ember-cli is not going to be serving up this file, not sure what this would do in production yet.

//# sourceMappingURL=ember-inflector.js.map

2) the directory structure under `node_modules/ember-inflector` contains a `lol` directory that mirrors the `bower_ember`  folder - I'm not sure if either folders are needed for the npm install, those folders are not in the github repo.

**Comment by stefanpenner** [comment]
should be addresed by the new addon
