### ISSUE TITLE
Issue getting this addon working

### ISSUE THREAD

**Issue by jcope2013** [stefanpenner/ember-inflector#59]
Versions on my systems

```
ember-cli: 0.1.3
Ember: 0.1.7
Watchman: 3.0.0
Mac OS X: 10.10
Node: 0.11.14
```

I followed the instructions on the first page

```
npm install --save ember-inflector
ember generate ember-inflector
```

I then imported both ember-inflector.js, and ember-inflector.js.map to my brocfile, this didn't seem to be the cause of my issues as I was having the same issues before I imported them also

and none of the suggested solutions have been working, I am getting undefined when I do 

```
Ember.Inflector.pluralize("taco");
```

and ember-inflector can't be resolved in the browser console when trying to import it

```
import Inflector from 'ember-inflector';
import {singularize, pluralize} from 'ember-inflector';
```

I tried taking out the node module and bower component then reinstalling just the bower component and just use the Ember.Inflector syntax in my app and still seeing same issues

any advice?

**Comment by davidmaitland** [comment]
Did you ever figure this one out? I'm having the same issue now. I have a feeling that the module is inherently broken.

**Comment by stefanpenner** [comment]
the current way this is distributed as an addon isn't ideal, as time permits we can get it up to snuff.

**Comment by fsmanuel** [comment]
try
`Ember.Inflector.inflector.pluralize("taco");`
