### ISSUE TITLE
Singularizes 'meta' as 'metum'

### ISSUE THREAD

**Issue by igorT** [stefanpenner/ember-inflector#67]
Of the things I expected to happen, this was not one of them. Not sure whether rails does the same thing? Does not seem very helpful

**Comment by stefanpenner** [comment]
rails

`'meta'.pluralize = 'meta'`

**Comment by stefanpenner** [comment]
although:

* https://github.com/stefanpenner/ember-inflector/blob/master/packages/ember-inflector/lib/system/inflections.js#L30
* https://github.com/rails/rails/blob/master/activesupport/lib/active_support/inflections.rb#L36

**Comment by fsmanuel** [comment]
rails

`'meta'.singularize => 'metum'`

**Comment by CodyEngel** [comment]
Just wanted to drop in and say `metum` is not a word: http://www.scrabblewordsolver.com//word-checker/metum/

I guess this is just matching Rails so I'll go yell in that direction but wanted to voice my opinion.
