### ISSUE TITLE
`singularize()` incorrectly lops off the beginning of dasherized, irregularly pluralized words

### ISSUE THREAD

**Issue by ultimatedelman** [stefanpenner/ember-inflector#79]
This is a problem when you have a model named something like "in-common-person", where in place of "person", any member of the [irregularPairs](https://github.com/stefanpenner/ember-inflector/blob/e19798c3759f2e46bc2b9ce7de36b85397b5d824/addon/lib/system/inflections.js#L56) list is at the end of the dasherized list.

To repro:

    Ember.String.singularize('in-common-person') // 'common-person'
    Ember.String.singularize('in-common-man') // 'common-man'
    //etc.

Because of this, any model named in this way is improperly referenced.

CC: @nathanhammond @chadhietala

**Comment by stefanpenner** [comment]
@ofbriggs got any free time to take a look?

**Comment by ofbriggs** [comment]
I'll investigate...

**Comment by stefanpenner** [comment]
@ofbriggs thank you kindly :)

**Comment by ultimatedelman** [comment]
I believe the error is (here)[https://github.com/stefanpenner/ember-inflector/blob/33825d61dc3a52c3aaef5b1f02fb179889531a98/addon/lib/system/inflector.js#L271-L279]. In the first flow, it's only returning the last part where as in the second flow it's appending the beginning part as well.

**Comment by ofbriggs** [comment]
@stefanpenner of course :)
@ultimatedelman I'm having trouble reproducing the cut. The area you're referring to appears valid, because that case is for a hard match. Can you help me out and give me a failing case?

**Comment by ultimatedelman** [comment]
@ofbriggs - did you try the examples I gave in the ticket?

    Ember.String.singularize('in-common-person') // 'commonPerson' instead of 'inCommonPerson'

**Comment by ultimatedelman** [comment]
@ofbriggs - I managed to cobble together a [working demo](http://emberjs.jsbin.com/kigahoroge/1/edit?html,js,output)

**Comment by ofbriggs** [comment]
@ultimatedelman I tried the examples, for me running the functions yield:
```
Ember.String.singularize('in-common-person') => 'in-common-person`
```
The ember.js in the demo is not using an up-to-date inflector it seems.

**Comment by nathanhammond** [comment]
Neither is Canary. I can't reproduce this inside of ember-inflector's tests, but can here: http://emberjs.jsbin.com/faguwohagu/1/edit?html,js,output

**Comment by nathanhammond** [comment]
Okay, this is an issue that existed previously, was present in Ember Data 1.0-beta16.1, and has since been updated in beta 17. Updated the JSBin, and now it works. This is safe to close.

**Comment by ofbriggs** [comment]
Thanks @nathanhammond :)

**Comment by stefanpenner** [comment]
thanks all for digging into this :)
