### ISSUE TITLE
Irregular Singularize of "Drives"

### ISSUE THREAD

**Issue by southpolesteve** [stefanpenner/ember-inflector#81]
Not sure if this is the proper place to report, but ran into this issue today:

``` javascript
var inflector = Ember.Inflector.inflector;
inflector.singularize('drives')
// > "drife"
```

I'm also happy to take a crack at fixing this, but just wanted to ensure this fix actually belongs upstream and not in the app itself

**Comment by stefanpenner** [comment]
some context:

the goal of this project is to

* provide the infrastructure for basic inflection
* provide default inflection rules that match those of ActiveSupport – which has frozen its inflection rules
* provide users the way to augment the base inflection rules.

```
  % bundle exec rails c                                                                         !13314
Loading development environment (Rails 4.2.1)
 :001 > "drives".singularize
 => "drife"
 :002 >
```

So the solution is for your application to specify the preference using `inflector.irregular(x,y)`

**Comment by southpolesteve** [comment]
Ah ok. That makes sense. Thanks for the quick reply!

**Comment by stefanpenner** [comment]
> Ah ok. That makes sense. Thanks for the quick reply!

no problem. It is in-fact strange, but english is a strange thing. :P
