### ISSUE TITLE
`singularize()` incorrectly singularizes "alumnus"

### ISSUE THREAD

**Issue by ultimatedelman** [stefanpenner/ember-inflector#82]
`Ember.Inflector.inflector.singularize('alumnus'); // "alumnu"`

**Comment by stefanpenner** [comment]
from the readme:

> Ember Inflector aims to be compatible with ActiveSupport::Inflector from Ruby on Rails

Rails has decided to freeze its default inflection rules, and to match parity so have we.

One can still add additional app specific inflections, see: https://github.com/stefanpenner/ember-inflector#usage for further examples of how one does this.
