### ISSUE TITLE
Regression for pluralization of 'price' in v1.9.0

### ISSUE THREAD

**Issue by timiyay** [stefanpenner/ember-inflector#85]
This morning, I attempted to upgrade my app to `ember-data` v1.13.9 which, in turn, upgraded `ember-inflector` to v1.9.0. This caused one of my model async relationships to fail, because `price` was incorrectly pluralized to `price`.

Previously, using `ember-data` v1.13.8 and `ember-inflector` v1.7.0, `price` was correctly pluralized to `prices`.

The symptom is that, when my model attempts to look up its associated `prices` via the `DS.ActiveModelAdapter`, it looks for `GET /api/price/:id` instead of `GET /api/prices/:id`.

To reproduce the bug, simply open a shell / console with Ember imported:

```js
// ember-inflector 1.7.0
inflector.pluralize('price');
// => 'prices'

// ember-inflector 1.9.0
inflector.pluralize('price');
// => 'price'
``` 

I attempted to workaround the issue, by adding my own inflection rule to an initializer...

```js
Ember.Inflector.inflector.irregular('price', 'prices');
```
...but the incorrect singular `/price` URL was still being requested.

**Comment by stefanpenner** [comment]
the pluralization appears to be correct, just double checked against our reference implementation:

```ruby
Loading development environment (Rails 4.2.3)
irb(main):001:0> 'price'.pluralize
=> "prices"
``

**Comment by stefanpenner** [comment]
there really don't appear to be any relevant differences between 1.7 and 1.9...

**Comment by stefanpenner** [comment]
@ofbriggs got any free moments to dig into this?

**Comment by timiyay** [comment]
@stefanpenner Thanks for the reply.

For extra context: I'm using `ember-mirage` v0.1.6 to provide a dummy backend to my app. Since I was able to repro the issue directly from `ember-inflector`, I concluded that `ember-mirage` wasn't to blame. I'll need to dig into this possibility, though, as it may be overriding my custom inflection initializer?

**Comment by adam-knights** [comment]
@stefanpenner I just posted this is ember data - price is getting hit by a rule on `rice` when I debug through.

**Comment by adam-knights** [comment]
Looking at the for loop where price gets hit with price I'd guess this did it https://github.com/stefanpenner/ember-inflector/commit/2e9bd63da79a9854a5e1ad2a94ea0b1d22f9707c

**Comment by adam-knights** [comment]
Changing lowercase.match(rule+"$") to something like lowercase.match("^"+rule+"$") might fix this, I'm at work else would submit a pr.

**Comment by miguelcobain** [comment]
https://github.com/stefanpenner/ember-inflector/compare/v1.7.0...v1.9.0

**Comment by adam-knights** [comment]
Ember data went from 1.6.2 to 1.90 in it's package.json https://github.com/emberjs/data/pull/3623/files

**Comment by stefanpenner** [comment]
> Ember data went from 1.6.2 to 1.90 in it's package.json https://github.com/emberjs/data/pull/3623/files

Yes this would make sense. there where some fixes (that appear to have introduced a bug) prior to 1.7

**Comment by ofbriggs** [comment]
It's this commit #83, that introduced the regression, uncountable matching was changed to match subwords instead of complete words which explains why the rule `rice` is getting hit. I'm going to look into  this more this weekend and update.

**Comment by stefanpenner** [comment]
thanks @ofbriggs you rock!

**Comment by ofbriggs** [comment]
I've submitted #86 to correct this behaviour.

**Comment by ofbriggs** [comment]
Closing issue now that #86 is in master.

**Comment by stefanpenner** [comment]
:)

**Comment by timiyay** [comment]
Thanks folks, really appreciate the fix.
