### ISSUE TITLE
singular and plural helpers are being registered the old way

### ISSUE THREAD

**Issue by grapho** [stefanpenner/ember-inflector#87]
it appears that the util for selecting how the helpers are registered is not working properly for me

https://github.com/stefanpenner/ember-inflector/blob/master/addon/lib/utils/make-helper.js

I am getting the deprecated version of the helper `makeBoundHelper`

Though I cant seem to find what version of the inflector i am running?

I am on ember 1.13.7, ember-data 1.13.8, and ember-cli 1.13.8

**Comment by jcope2013** [comment]
bump to ember-data 1.13.9 will fix it

**Comment by grapho** [comment]
k thanks! i suppose we can close this then :false-alarm:
