### ISSUE TITLE
Irregular rule for unitOfMeasure to unitsOfMeasure does not work

### ISSUE THREAD

**Issue by adam-knights** [stefanpenner/ember-inflector#95]
I tried adding

    inflector.irregular('unitOfMeasure', 'unitsOfMeasure');

To my app and it doesn't work, it hits /api/unitOfMeasure, it should now be hitting /api/unitsOfMeasure

I created a unit test in /tests/unit/inflector-test.js that fails on both asserts in latest master:

```
test('unit of measure', function(assert) {
  inflector.irregular('unitOfMeasure', 'unitsOfMeasure');

  assert.equal(inflector.singularize('unitsOfMeasure'), 'unitOfMeasure', 'irregular singularization rule was applied');
  assert.equal(inflector.pluralize('unitOfMeasure'), 'unitsOfMeasure', 'irregular pluralization rule was applied');
});
```

-----
I had a quick debug, it seems to find the irregular rule ok and populate `substitution` in the for loop, but then I think the return in that loop of `return word.replace(rule, substitution);` doesn't do the job as word is `unitOfMeasure` and rule is `unitofmeasure`, so there is no match due to the casing?

**Comment by adam-knights** [comment]
The above research stemmed from me trying to define plurals in DS.RESTAdapter.extend, and this working for all but unitOfMeasure: unitsOfMeasure. I'm guessing this feeds into ember inflector?

**Comment by adam-knights** [comment]
@fivetanley Any thoughts on whether this is a bug that would be affecting me defining this in Ember Data, or should I go back to Ember data and post this there?

**Comment by stefanpenner** [comment]
We aim todo whatever the rails inflector does, if someone wants to check we can decide if this is a bug or not.

**Comment by fsmanuel** [comment]
```ruby
'unitOfMeasure'.pluralize # => "unitOfMeasures"
'unitsOfMeasure'.singularize # => "unitsOfMeasure"
```

**Comment by adam-knights** [comment]
@fsmanuel thats with an irregular rule defined?

**Comment by fsmanuel** [comment]
@adam-knights `rails c` i have nothing defined. It's just what the rails inflector does.

**Comment by fsmanuel** [comment]
@adam-knights have you seen https://github.com/emberjs/data/issues/3802

**Comment by fsmanuel** [comment]
and here https://github.com/emberjs/data/pull/3888#issuecomment-164786076

**Comment by fsmanuel** [comment]
@adam-knights what version of ember-data are you using. still seems to be a problem...

**Comment by adam-knights** [comment]
I'm stuck on 1.13.15 currently, happy to revisit/test this when we are able to move upto a newer release

**Comment by fsmanuel** [comment]
which adapter?

**Comment by adam-knights** [comment]
RESTAdapter, so for plural of this example I would do:

    export default DS.RESTAdapter.extend(DataAdapterMixin, {
      plurals: {
        unitOfMeasure: 'unitsOfMeasure'
      }
    });

**Comment by fsmanuel** [comment]
@adam-knights if the problem only occurs with the path you can patch `pathForType`
https://github.com/emberjs/data/blob/v1.13.15/packages/ember-data/lib/adapters/build-url-mixin.js#L319

But i guess the next will be the payload...

**Comment by escobera** [comment]
@stefanpenner any new on this one? 
I'm still affected by this.
If confirmed as a bug I can help come up with the solution, seems pretty straightforward.

**Comment by fsmanuel** [comment]
@escobera which version of ember, ember-data and ember-inflector are you using?

**Comment by adam-knights** [comment]
Here is a twiddle. In adapters/application.js the plural is defined but not picked up as it continues to try to hit the wrong API. https://ember-twiddle.com/7a1de453247619a45f3b39915ab3be90?fileTreeShown=false&numColumns=2&openFiles=routes.application.js%2C

**Comment by fsmanuel** [comment]
I'm on it

**Comment by fsmanuel** [comment]
@adam-knights and @escobera can you try the new version? I guess we have to inform the other addons about the fix.

**Comment by adam-knights** [comment]
@fsmanuel thanks - Ember data is ^1.9.4, so when I get a chance i'll clear out my node/bower folders to pull in 1.9.5 and see
